### ISSUE TITLE
Special scoring

### ISSUE THREAD

**Issue by mebegu** [awesome-comp302/chewy-lokum-legend-v2#7]
There is no scoring on both generation and explosion of the special lokums. The suggestion is handle the scoring separately from regular erase scoring. Also, scoring can be done in special generation and erase rule classes.

**Comment by TheVulch** [comment]
Could you be more specific about the scoring on "generation" of special lokums? Do you mean that there should be scoring whenever a special lokum is created?
Couldn't this be done in the erasing section still? If we have a pattern of lokums that generate a special lokum, we should know that this has to happen in the erasing section...right?

**Comment by mebegu** [comment]
![image](https://cloud.githubusercontent.com/assets/9113962/5693687/ffabca24-9931-11e4-8795-952eface6651.png)
![image](https://cloud.githubusercontent.com/assets/9113962/5693694/55bb0240-9932-11e4-8fb6-432acc5b9bf5.png)

**Comment by mebegu** [comment]
The requirements says there should be generation scoring.
You can do it by any way, that was just a suggestion.
Dont confused with Special Lokum Combos' scoring, we dont have all of them yet. 
But, you can also handle that issue, if you want. (Issue number: 6   "Special+Special move")

**Comment by LineIntegral** [comment]
See StandardScoringRules.getCreationScore

**Comment by TheVulch** [comment]
@LineIntegral does that mean we already have creation scoring?
@mebegu Yeah, I'll work on #6 as well.

**Comment by LineIntegral** [comment]
Generation score should be working. Pull the new version and check it.

**Comment by LineIntegral** [comment]
@TheVulch  Are you working on this issue.

**Comment by mebegu** [comment]
**Resolved!**
